[package]
name = "binterop-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
backend = { path = "../backend" }
binterop = { path = "../../binterop" }
quote = "1.0.36"
syn = "2.0.72"
